[package]
name = "NeoQube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
obws = "0.11.5"
twitch-irc = "5.0.1"
twitch_api = "0.7.0-rc.7"
